"""LaTeX primitives for the generated tables — `PLAN.md` 10.1.

Two rules hold this together.

**Nothing measured is ever typed by hand.** Every number in the report comes from a
recorded JSON file through this code, so a number in the PDF and a number in
`verification/measured_facts.json` cannot disagree.

**Nothing missing is ever rendered as a number.** A builder with no data emits `\\TODO{}`,
which `main.tex` defines as red bold text — *"a build with TODOs left in is not final"*. The
alternative failure, an empty cell or a plausible `0.00`, is the one that survives to a
submitted PDF.

The escaping matters more than it looks. Ten characters are special to LaTeX, and the
consequences differ sharply:

* `%` **comments out the rest of the line**, so an unescaped percent in a caption silently
  deletes the `\\label` after it and every reference to the table becomes `??`;
* `&` and `\\\\` break the tabular alignment, which at least fails loudly;
* `_` and `^` are errors outside maths, which also fail loudly.

The first is the dangerous one, and it is the character this project's data is most full of.
"""

from __future__ import annotations

import re
from collections.abc import Iterable, Sequence
from typing import Any

#: Replacement per special character. This has to be applied in **one pass**: sequential
#: `str.replace` calls cannot work, because the replacements themselves contain special
#: characters. Rewriting `\` first gives `\textbackslash{}`, and the later brace rule then
#: mangles it into `\textbackslash\{\}`, which prints as literal `\{}` on the page. A
#: single regex substitution never revisits what it just wrote.
_ESCAPES = {
    "\\": r"\textbackslash{}",
    "&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#",
    "_": r"\_", "{": r"\{", "}": r"\}",
    "~": r"\textasciitilde{}", "^": r"\textasciicircum{}",
}
_SPECIAL = re.compile("|".join(re.escape(c) for c in _ESCAPES))

TODO = r"\TODO{}"


def escape(text: Any) -> str:
    """Make an arbitrary string safe to drop into a LaTeX document."""
    return _SPECIAL.sub(lambda m: _ESCAPES[m.group()], str(text))


def num(value: float | None, digits: int = 2, *, percent: bool = False) -> str:
    """A number, or a visible TODO when it was never measured.

    `None` means *not measured*. It must not become `0.00`: a zero is a claim.
    """
    if value is None:
        return TODO
    return f"{value:.{digits}f}" + (r"\%" if percent else "")


def ci(value: float | None, lo: float | None = None, hi: float | None = None,
       digits: int = 1) -> str:
    """A point estimate with its interval, as `PLAN.md` 7.4 requires of every cell."""
    if value is None:
        return TODO
    if lo is None or hi is None:
        return f"{value:.{digits}f}"
    return (f"{value:.{digits}f}\\,\\tiny{{[{lo:.{digits}f}, {hi:.{digits}f}]}}")


def row(cells: Iterable[Any]) -> str:
    """One tabular row. Cells are joined, never escaped — they may hold LaTeX already."""
    return " & ".join(str(c) for c in cells) + r" \\"


def tabular(spec: str, header: Sequence[Any], rows: Sequence[str], *,
            midrules_before: Sequence[int] = ()) -> str:
    """A booktabs tabular. `midrules_before` indexes into `rows`."""
    out = [f"\\begin{{tabular}}{{{spec}}}", r"\toprule", row(header), r"\midrule"]
    for i, r in enumerate(rows):
        if i in midrules_before:
            out.append(r"\midrule")
        out.append(r)
    out += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(out)


def table(name: str, caption: str, label: str, body: str, *, wide: bool = False,
          note: str = "") -> str:
    """A complete float, with the provenance comment the skeleton stubs already carry."""
    env = "table*" if wide else "table"
    parts = [f"% {name} — generated by: cdt-report --what {name.removeprefix('tab_')}",
             "% Do not edit by hand; edits are overwritten on the next build.",
             f"\\begin{{{env}}}[t]", r"\centering",
             f"\\caption{{{caption}}}", f"\\label{{{label}}}", body]
    if note:
        parts.append(f"\n\\vspace{{2pt}}\n\\footnotesize{{{note}}}")
    parts.append(f"\\end{{{env}}}")
    return "\n".join(parts) + "\n"


def has_todo(text: str) -> bool:
    """Whether a generated fragment still contains an unmeasured cell."""
    return r"\TODO" in text


__all__ = ["TODO", "ci", "escape", "has_todo", "num", "row", "table", "tabular"]
